# -*- coding: utf-8 -*-
"""narrative_gap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5v1chzu5mVPHGXqPXbenkPxolCwm150

# Exercise

* Narrative gap/storytelling

* This exercise is designed to help you identify and articulate `narrative gaps` in data storytelling.

* You will work with a sample dataset containing website traffic, bounce rates, and conversion rates to uncover discrepancies between different metrics.

* The goal is to analyze these metrics, formulate questions about observed trends, and build a narrative that connects seemingly conflicting data points to tell a coherent story.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Sample Data: Website Traffic and Sales
data = pd.DataFrame({
    'Day': range(1, 8),
    'Visitors': [1000, 1100, 1050, 1200, 1500, 1600, 1550],
    'Bounce_Rate': [40, 42, 41, 39, 65, 68, 70],
    'Conversion_Rate': [5, 5, 4.8, 5.2, 2.1, 1.8, 1.5]
})

"""## Solution"""

def plot_narrative_gap():
    # Chart 1: Traffic is growing
    plt.figure(figsize=(5, 3))
    sns.lineplot(data=data, x='Day', y='Visitors', marker='o')
    plt.title("Total Website Visitors")
    plt.show()

    # Chart 2: Bounce rate spiked
    plt.figure(figsize=(5, 3))
    sns.lineplot(data=data, x='Day', y='Bounce_Rate', color='red')
    plt.title("Bounce Rate Percentage")
    plt.show()

    # Chart 3: Conversion dropped
    plt.figure(figsize=(5, 3))
    sns.barplot(data=data, x='Day', y='Conversion_Rate')
    plt.title("Sales Conversion Rate")
    plt.show()

plot_narrative_gap()

narrative_audit = {
    "Transition_1_to_2": {
        "Observation": "Traffic is hitting record highs in the second half of the week.",
        "The Question": "Is this high-volume traffic actually high-quality traffic?",
        "Bridge": "To find out, we need to look at the **Bounce Rate** to see if people are sticking around."
    },
    "Transition_2_to_3": {
        "Observation": "Bounce rates nearly doubled as traffic increased.",
        "The Question": "How did this inability to retain users impact our bottom line?",
        "Bridge": "We will now examine **Conversion Rates** to quantify the cost of this technical friction."
    }
}

print(narrative_audit)

'''
## Key Takeaways
# 
# 1. High traffic volume doesn't necessarily translate to high-quality traffic.
# 2. A spike in bounce rate indicates poor user experience or irrelevant content.
# 3. The drop in conversion rate is directly tied to the increase in bounce rate.
# 4. Data storytelling requires connecting seemingly disconnected metrics to form a coherent narrative.
# '''